### ISSUE TITLE
False positive and can no longer log into Playstation on my PC

### ISSUE THREAD

**Issue by mikeyplaut** [camtheperson/get-my-ps5#10]
Was able to get around 400pings before getting a false positives each time now. Now I can't even login to Playstation on chrome on my pc. (I can still login on my phone using wifi)

**Comment by sargas333** [comment]
reloaded the updated version and it is running now without false positive. Over 500 tries. Thanks for the update!

**Comment by camtheperson** [comment]
Just merged a fix. Update here: https://twitter.com/CamThePerson/status/1337153618277851136

Pull the latest, run npm (or yarn) install, and it should be good.

**Comment by dronf** [comment]
I was on the version just before this fix(i pulled about 30 mins before it was commited :/ ), and it got me right into the queue, but I was unable to login to playstation direct, even after resetting my password and jumping on a VPN.  I tried another machine with a different IP, and was able to get in.   Would your most recent fix have fixed that issue, or did i get hit with an unrelated softban?

thanks!

**Comment by alechemy** [comment]
@dronf I encountered the exact same issue -- and was also running the version before this PR. But I did manage to eventually log in to PS Direct by navigating to https://direct.playstation.com/en-us in a new window. I then closed that window, jumped back to the product page, refreshed, and then managed to place my order. 

This doesn't answer your question, but in case you encounter the same issue next time, perhaps you could try this workaround?

**Comment by dronf** [comment]
Will give that a try...hopefully they drop more inventory soon!

thanks
