### ISSUE TITLE
Can't login to psn besides when in an incognito tab

### ISSUE THREAD

**Issue by mikeyplaut** [camtheperson/get-my-ps5#13]
Can you make it so it opens an incognito window?

**Comment by Jswill11AZ** [comment]
Try this.

https://www.howtogeek.com/137466/how-to-always-start-any-browser-in-private-browsing-mode/#:~:text=If%20you're%20using%20a,and%20then%20the%20word%20incognito.

**Comment by mikeyplaut** [comment]
Doing that just makes it so when I open chrome it's in incognito mode, the program still opens into normal chrome

**Comment by mikeyplaut** [comment]
Made a fix index.js @ line 27
open(playstationType[choice].url, {app: ['chrome', '--incognito']});

**Comment by mikeyplaut** [comment]
The program works great btw, I was put into queue right away, got into site few minutes after stock dropped, but was unable to login so😣

**Comment by Jswill11AZ** [comment]
Nice!! So what was the issue not running in incognito? And now if it runs in incognito you just have to sign in psn when you hit the queue??

I read something this morning saying Sony set a work around to log IPs that ping the site like a bot would. So I didn’t try it today, went old fashioned and missed out. Will try it tomorrow

**Comment by mikeyplaut** [comment]
Yea I'm pretty sure my ip got flagged or something. I've tried clearing chrome browser history/cookies and just can't seem to login. If I try in an incognito tab than I can login no problems, which makes me think it's not an ip problem. Also some people have the problem of not being able to get into the queue right away because they sit on the site before the queue starts, and using a new incognito page is supposed to be the most reliable way to get into the queues

**Comment by Jswill11AZ** [comment]
That is exactly what happened to me today. Was sitting on the sight in incognito and manually switching between console and digital and it would not put me in the queue. Updating line 27 with your addition. Hope there is a drop tomorrow. 

Thanks and good luck.
