### ISSUE TITLE
Cannot Run Bot After Successful Launch and Close

### ISSUE THREAD

**Issue by midshoreit** [camtheperson/get-my-ps5#16]
Here's one for ya:
 I can only run the bot once. If I close it correctly, and then later open a new elevated command prompt, open the working directory, and try to run, it just sits there. Tried `npm install` - same thing, sites there. Tried `npm run watch` - just sits there. If I reboot my system, I can run the bot again. Thoughts? Last tested with v1.1.0.

I'm running W10 Pro with an i7 8th gen, 40GB RAM, 1TB M.2 SSD, etc. My a/v software is Emsisoft Anti-Malware, but I've set my working directory as an exclusion

**Comment by camtheperson** [comment]
Any error messages?

**Comment by midshoreit** [comment]
Alright, dug deeper. It appears to be an A/V issue. Even with exceptions set for the entire folder, the FILE GUARD feature of my security program was actually stopping all the external actions of the script, from the sounds to the site openings. Disabled that feature and everything works. I would only suggest at this point to TRY and make the alert sound a windows event. Currently when the alarm fires it opens the MP4 in the defaults audio player, which in my case took a few extra seconds because of a TON of background processes I had going. So if someone was relying on hearing the alert, it COULD have a significant delay between firing and actually opening and playing. If it was a Windows event generating a system sound it would be instant. Just thoughts. Much respect for your work bro.

**Comment by camtheperson** [comment]
@midshoreit Perfect. Glad to hear you figured it out.

Thanks for your feedback on the alarm. A few other people noted that as well, so I've moved the `open` action before playing the sound to ensure it isn't delayed.

Closing this out.
