### ISSUE TITLE
Specifying a custom root CA

### ISSUE THREAD

**Issue by adamsatar** [camtheperson/get-my-ps5#18]
Hi Cam, 

Really great work for spinning up this script. Works as advertised. My js knowledge is limited, so instead of hacking around, thought I'd just ask: where would be the best place to specify a CA file? I'm currently getting

UnhandledPromiseRejectionWarning: Error: net::ERR_CERT_AUTHORITY_INVALID at https://direct.playstation.com/en-us/consoles/console/playstation5-console.3005817

**Comment by camtheperson** [comment]
Are you getting this error immediately, or after a number of retries? If so, how many?

**Comment by shahmirn** [comment]
@camtheperson The only thing I can think of is people being behind a corporate firewall, which might cause this issue. 
The puppeteer launch code can be modified to ignore certificate errors. See: https://github.com/puppeteer/puppeteer/pull/177 or https://stackoverflow.com/q/55207690

**Comment by outphase84** [comment]
This would indicate that a non-trusted CA is in play, which would be somewhat common if running in a corporate environment or a prosumer environment with SSL inspection enabled.

**Comment by adamsatar** [comment]
> Are you getting this error immediately, or after a number of retries? If so, how many?

It's immediate and a product of the network environment. Was just looking for a way to deal. I'll check out what @shahmirn said. 

Thanks!
