### ISSUE TITLE
Saying Stock Found When Line Isn't Up

### ISSUE THREAD

**Issue by YoungPhoenix09** [camtheperson/get-my-ps5#2]
Hello,

I am finding that when I execute the `run watch` command it is instantly popping up and saying the queue is open, even though it is not.  Is there something I'm not doing correctly?  I followed the instructions for setting up. and I'm currently running v12.18.1 of node.  Attached is a screenshot of what I see happen as soon as I run it, as well as verification of my node version.  Please let me know what other details I can provide.  Thank you for your efforts!

![1607552375595blob](https://user-images.githubusercontent.com/9001383/101695827-2e5d0500-3a43-11eb-8bcd-7e50030cf037.jpg)

**Comment by robbiered** [comment]
same issue

**Comment by camtheperson** [comment]
@YoungPhoenix09 @robbiered Can you try using the latest LTS version of Node (14.15.1) and letting me know if that resolves the issue? Thanks.

**Comment by robbiered** [comment]
I am 

PS E:\a\get-my-ps5> node -v
v14.15.1

**Comment by robopotamus** [comment]
Getting the same thing. Just installed the latest node.js as well and same issue.

**Comment by camtheperson** [comment]
@robbiered @robopotamus Okay please also provide the following info when you get a chance:

- Platform (Windows? Mac? What version?)
- npm version

I'll be doing some more troubleshooting tonight, hoping to iron out these issues before the next PS5 drop.

**Comment by robopotamus** [comment]
@camtheperson 

Windows 10 Pro Build 19042
npm v7.0.15

**Comment by robbiered** [comment]
> @robbiered @robopotamus Okay please also provide the following info when you get a chance:
> 
> * Platform (Windows? Mac? What version?)
Windows 10 build 19042.630 AND Mac OS Big Sur
> * npm version
Windows - 6.14.8
Mac - 7.0.15
> 
> I'll be doing some more troubleshooting tonight, hoping to iron out these issues before the next PS5 drop.

Same issue on both machines

**Comment by YoungPhoenix09** [comment]
@camtheperson
Thanks for looking into it!  Just a heads up, I just updated my node version and am still having the same issue.
Platform: Mac OS Catalina (10.15.7)
node version: 14.15.1
npm version: 6.14.8

**Comment by jcarman81** [comment]
I’m completely lost with the setup. Anyone help a noob? 

Joe Carman

**Comment by robopotamus** [comment]
@camtheperson I installed https://1.1.1.1/ and then reset my ipconfig. Went from tapping out at 2 pings to currently sitting at 40+ without false positives

**Comment by jvandorn** [comment]
FYI, works fine for me, installed today (post drop): MacOS Mojave 10.14.16, node: 14.15.1, npm: 6.14.8

**Comment by YoungPhoenix09** [comment]
> @camtheperson I installed https://1.1.1.1/ and then reset my ipconfig. Went from tapping out at 2 pings to currently sitting at 40+ without false positives

Tried installing 1.1.1.1 and renewed my IP lease.  Still getting false positives here.

**Comment by youenjoymyself** [comment]
Having same issue with false positives.  False positive can happen on the first try or like 4th or 5th, isn't the first attempt every time.
Windows 10 1909
NPM 6.14.8
Node: 14.15.1
Flushed dns and tired 8.8.8.8 and 1.1.1.1 with same result.

**Comment by dronf** [comment]
I think the redirect and captcha is mainly triggered by load. I installed this and hour or two after today's drop, and immediately got a false positive, but I think it was because so many people were hitting the site still.  Even though it had been sold out for hours, I still got the captcha when manually browsing there.

**Comment by youenjoymyself** [comment]
> I think the redirect and captcha is mainly triggered by load. I installed this and hour or two after today's drop, and immediately got a false positive, but I think it was because so many people were hitting the site still. Even though it had been sold out for hours, I still got the captcha when manually browsing there.

Yeah I think you are right.  I have been doing some testing and it will send me to direct-queue.playstation.com sometimes when manually browsing to the site.

**Comment by camtheperson** [comment]
@youenjoymyself I just observed this myself. Looks like Sony may have wised up.

Steps to replicate:
1. Go to https://direct.playstation.com/en-us/consoles/console/playstation5-console.3005816
2. Occasionally, I'll get send to a page with reCAPTCHA and a URL starting with "https://direct-queue.playstation.com/softblock/"

Welp.

**Comment by RenewedKeys** [comment]
> 
> 
> @youenjoymyself I just observed this myself. Looks like Sony may have wised up.
> 
> Steps to replicate:
> 
>     1. Go to https://direct.playstation.com/en-us/consoles/console/playstation5-console.3005816
> 
>     2. Occasionally, I'll get send to a page with reCAPTCHA and a URL starting with "https://direct-queue.playstation.com/softblock/"
> 
> 
> Welp.

New update to softblock seems to have fixed the issue...

**Comment by YoungPhoenix09** [comment]
@RenewedKeys what do you mean by softblock?

**Comment by brittromo** [comment]
So, because of this Softblock issue, this CLI code no longer works, is that correct?

**Comment by youenjoymyself** [comment]
At the moment it seems to be working fine for me...I don't know if the occasional redirects are purely load based or if they are flagging your client as suspicious and want you to do a reCaptcha.  I have noticed in the past few days if I open the site from multiple different browsers it would send me to a reCaptcha even when the queue wasn't up.  Maybe I was getting flagged for my activity?  I'm going to try it today hopefully it keeps working

**Comment by spencerlichtenstein** [comment]
Running Windows 10 Pro build 19042 and installed this morning. No issues so far, I have been running for about 14 minutes and have ~170 tries so far with no issues. This is excellent, hoping for the best @camtheperson . Will advise on any issues.

**Comment by camtheperson** [comment]
Update on this issue: https://twitter.com/CamThePerson/status/1337073452201611264?s=20

Closing this ticket out for now. The temporary workaround is to run the script again, although I have an idea for a fix I'll be able to test as soon as I can hit the actual queue page again.
