### ISSUE TITLE
After 2632 tries, TimeoutError occured

### ISSUE THREAD

**Issue by koalabuttz** [camtheperson/get-my-ps5#25]
Windows 10, fresh Node install. Running through Windows Terminal.

Everything runs and the test commands work great, but I left the script running overnight and when I woke up the next morning I found this message. 
![Screenshot 2020-12-11 140546](https://user-images.githubusercontent.com/27229333/101944074-1cea3900-3bba-11eb-9edc-71649c7fe5e9.png)
There are a few warnings, but most obvious one to me is "TimeoutError: Navigation timeout of 30000 ms exceeded"

I wish I had more insight into what caused this, but it seems like an important issue if this script is going to accomplish what it sets out to do. I'll be leaving it on overnight again and will report back if I can replicate it.

**Comment by Qiming-C** [comment]
I had the error, I assume maybe its network connection error since my internet connection is unstable I have this error message every hundred tries

**Comment by koalabuttz** [comment]
This is quite possible, Comcast has dropped my network connection in the wee hours of the morning, presumably for maintenance, before.

**Comment by ManOrMonster** [comment]
I also received the error today. It's produced by Puppeteer.

https://ourcodeworld.com/articles/read/1106/how-to-solve-puppeteer-timeouterror-navigation-timeout-of-30000-ms-exceeded

In utils.js, I added this at line 48: `await page.setDefaultNavigationTimeout(0);` right before `await context.close();`. Not sure if that's the right place for it, but it's working so far. I believe you'll need to run `npm install` again after changing the code.

**Comment by ManOrMonster** [comment]
FYI, I just found out there was a drop an hour ago and I wasn't notified at all. So either this script is not working or my timeout fix broke it.

**Comment by koalabuttz** [comment]
I applied your fix before the drop hit and it alerted me properly, I just happened to be away when it happened. I just think there's just some bugs to be weeded out. I restarted it after the drop and literally just passed try 2632 and going strong, so we'll see if by tomorrow it's still going properly.

**Comment by outphase84** [comment]
@ManOrMonster @koalabuttz Avoid this "fix" -- you're telling puppeteer to never time out by doing that.  We *want* it to time out if PS Direct is being unresponsive, so we can abort the attempt and try again.

I have a pull request pending that adds error handling that will resolve this issue

**Comment by koalabuttz** [comment]
@outphase84 Thank you for the clarification! Appreciate you putting in that work. I deleted that line of code and tried to use your pull request overnight, but encountered this error after it failed to connect, perhaps it is related?
![Screenshot 2020-12-12 110909](https://user-images.githubusercontent.com/27229333/101988888-9e999f80-3c6a-11eb-88be-07abc477a404.png)

**Comment by outphase84** [comment]
Hang tight, let me do some regression testing.

**Comment by outphase84** [comment]
@koalabuttz Sorry, I'm an idiot.  I manually pulled in my changes to github and missed a change.  Stand by, syncing my fork and updating the PR.

In the interim, you can update line 62 to mitigate this:

```
    if (responseBody && responseBody.indexOf("queue-it_log") > 0 && 
```

**Comment by koalabuttz** [comment]
@outphase84 Haha you're no idiot, you're human 😊 and one that definitely understands what they're looking at more than I do! Good catch.
