### ISSUE TITLE
Some users are directed to the product page instead of the queue

### ISSUE THREAD

**Issue by camtheperson** [camtheperson/get-my-ps5#26]
Consider directing users to the queue directly instead:

Console edition: https://direct-queue.playstation.com/?c=sonyied&e=psdirectprodku1&t=https%3A%2F%2Fdirect.playstation.com%2Fen-us%2Fconsoles%2Fconsole%2Fplaystation5-console.3005816&cv=1089561812&cid=en-US

Digital edition: https://direct-queue.playstation.com/softblock/?c=sonyied&e=psdirectprodku1&t=https%3A%2F%2Fdirect.playstation.com%2Fen-us%2Fconsoles%2Fconsole%2Fplaystation5-digital-edition-console.3005817&cid=en-US

**Comment by mamadou-diallo** [comment]
Let me take care of this !

**Comment by ManOrMonster** [comment]
Remove `/softblock` from the digital URL.

**Comment by camtheperson** [comment]
@mamadou-diallo Please branch from/target your PR to `camtheperson:rc/1.2.0` (https://github.com/camtheperson/get-my-ps5/tree/rc/1.2.0) when it's ready to review. Thanks!
