### ISSUE TITLE
Couple of quick questions.

### ISSUE THREAD

**Issue by azazael13** [camtheperson/get-my-ps5#28]
I saw on twitter that this was potentially not working after a javascript change on Sony's side yesterday, is that still the case?

Is it possible to just have it open the site and get in the queue right away? I don't need it to put it in my cart and check out for me, I just need to get in the damned queue right away. Beyond that I still have to put all my payment info in since I can't find a way of getting that saved ahead of time without buying something (unless I am missing something).

Thanks.

**Comment by ManOrMonster** [comment]
It didn't work for me on the drop today. I have one running for disc and one for digital, never fired at all.

**Comment by aleath** [comment]
I got the alert today, but the browser didn't open. I'm fine with just the alert, though.

**Comment by gconcepcion** [comment]
It worked for me on the drop today

**Comment by Jswill11AZ** [comment]
It worked on the drop for me. However, I saw tweet notification on phone first and got in there. This was about 4 seconds slower, which equated to an additional 8 minutes of estimated wait time.

**Comment by outphase84** [comment]
Currently working with a few bugs -- closing this issue as it's more of a general question and it's been answered
