### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by luitjens** [camtheperson/get-my-ps5#29]
I'm getting the following error on win10:

Error log:

C:\Users\username\Documents\GitHub\get-my-ps5>npm run watch

> get-my-ps5@1.1.0 watch C:\Users\username\Documents\GitHub\get-my-ps5
> node index

Which version would you like? (disc or digital) disc
Would you like to hear a loud, annoying alarm when we find your PS5? (Y or N) Y
Searching for PlayStation 5 disc edition...
(node:31888) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (C:\Users\username\Documents\GitHub\get-my-ps5\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:79:23)
    at async C:\Users\username\Documents\GitHub\get-my-ps5\index.js:33:84
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by outphase84** [comment]
@luitjens can you try issuing the command "npm i puppeteer" from the get-my-ps5 directory?

**Comment by luitjens** [comment]
thanks that worked.

**Comment by outphase84** [comment]
PR created to update readme with steps to resolve
