### ISSUE TITLE
No JavaScript enabled in the response.data

### ISSUE THREAD

**Issue by cristiang777** [camtheperson/get-my-ps5#3]
Trying this in ChromeOS (Google Pixelbook) and the reponse.data contains something like this (instead of the page content):

```
<div class="nojavascript alert alert-error">\n' +
    `        <p>The site requires JavaScript to be enabled! The browser you're using doesn't support JavaScript, or has JavaScript turned off. <br>Try again with a browser that has JavaScript turned on. <a href="https://www.enable-javascript.com/" target="_blank">Learn More</a></p>\n` +
    '    </div>\n' +
```

node version: v14.15.1
npm version: 6.14.9

Edit: Same on Mac OS Big Sur (11) / node v15.3.0 / npm 7.0.14

**Comment by camtheperson** [comment]
Yep. This is a legitimate, bot-breaking issue.

If anyone has time to look into this before tonight, I'd greatly appreciate it. Otherwise, the bot will not work in it's current state.

Update here: https://twitter.com/CamThePerson/status/1337105964374269953

**Comment by jaredhensley** [comment]
@

> Yep. This is a legitimate, bot-breaking issue.
> 
> If anyone has time to look into this before tonight, I'd greatly appreciate it. Otherwise, the bot will not work in it's current state.
> 
> Update here: https://twitter.com/CamThePerson/status/1337105964374269953

How does this break the bot? The server sees that this request is not coming from a browser and returns this response? can we mask the headers somehow?

**Comment by cristiang777** [comment]
I tried adding a user agent to axios but that didn't change the result. Not sure how to enable (or even if possible) the JavaScript engine in axios.

**Comment by jaredhensley** [comment]
> I tried adding a user agent to axios but that didn't change the result. Not sure how to enable (or even if possible) the JavaScript engine in axios.

I think we could simply handle this response by parsing it and treating it as an active queue scenario.  Do you get this response on each call or only when the queue goes live?

**Comment by jaredhensley** [comment]
or we could make this an actual web app and have these requests go out from the browser and then redirect accordingly.

**Comment by damm** [comment]
If content-type is set to application/json axios should parse the javascript automatically according to [this](https://masteringjs.io/tutorials/axios/response-body#:~:text=Automatic%20Parsing,response%20into%20a%20JavaScript%20object.&text=Keep%20in%20mind%20that%20the%20response%20headers%20are%20sent%20by%20the%20server.)

**Comment by camtheperson** [comment]
@jaredhensley This breaks the bot because my initial GET will always (or at least often) return false negatives now.

Here's the response.data value for the initial GET
```
  data:
   '<!DOCTYPE html>\n<html>\n<head>\n\n    <script type=\'text/javascript\'>\n        document.location.href = \'/?c=sonyied&e=psdirectprodku1&t=https%3A%2F%2Fdirect.playstation.com%2Fen-us%2Fconsoles%2Fconsole%2Fplaystation5-console.3005816&cid=en-US&tsr=1607630191&tsh=6429a7aaf8a20384a3e979c98c8b1fbc9d233dec5ae09aef0c060fa07e9a1880\';\n    </script>\n    <style type="text/css">\n        body {\n            color: #000;\n            font-family: Arial,Helvetica,sans-serif;\n            font-size: 11px;\n        }\n\n        .alert-error {\n            background-color: #f2dede;\n            border-color: #eed3d7;\n        }\n\n        .nojavascript {\n            border: 1px solid red !important;\n        }\n\n        .alert {\n            padding: 8px 35px 8px 21px;\n            font-weight: normal;\n            font-size: 14px;\n            -webkit-text-shadow: 0 1px 0 rgba(255,255,255,0.5);\n            text-shadow: 0 1px 0 rgba(255,255,255,0.5);\n            border: 1px solid #fbeed5;\n            -webkit-border-radius: 4px;\n            -moz-border-radius: 4px;\n            border-radius: 4px;\n        }\n    </style>\n</head>\n<body>\n    <div class="nojavascript alert alert-error">\n        <p>The site requires JavaScript to be enabled! The browser you\'re using doesn\'t support JavaScript, or has JavaScript turned off. <br>Try again with a browser that has JavaScript turned on. <a href="https://www.enable-javascript.com/" target="_blank">Learn More</a></p>\n    </div>\n</body>\n</html>' 
```

You can see this in action on the client side by using the following steps to replicate:
1. Open an incognito or private window.
2. Open DevTools, go to the Network tab, and preserve the network log.
3. Go to https://direct.playstation.com/en-us/consoles/console/playstation5-console.3005816
4. Observe that the initial GET results in a 302 redirect, which shuffles users to something like: https://direct-queue.playstation.com/?c=sonyied&e=psdirectprodku1&ver=v3-javascript-3.6.3&cver=144&man=PS%20Direct%20Prod%20KU%20Action&t=https%3A%2F%2Fdirect.playstation.com%2Fen-us%2Fconsoles%2Fconsole%2Fplaystation5-console.3005816&kupver=akamai-1.0.2

This redirect seems to happen often for me, and it checks that JavaScript is enabled. Since my bot is effectively running from Node, JavaScript isn't enabled.

We need a workaround for this.

**Comment by alexsheehan** [comment]
> or we could make this an actual web app and have these requests go out from the browser and then redirect accordingly.

I thought about this too, but wouldn't this have the same fate as if we just sat on the page and refreshed manually (which doesn't work)?

**Comment by camtheperson** [comment]
Just merged a fix. Update here: https://twitter.com/CamThePerson/status/1337153618277851136

Pull the latest, run npm (or yarn) install, and it should be good.
