### ISSUE TITLE
has anyone got the UK Urls that are needed for this to work on the UK store ? 

### ISSUE THREAD

**Issue by johnnyboy007** [camtheperson/get-my-ps5#35]

**Comment by johnnyboy007** [comment]
Ive altered some of the Urls myself but Im not sure exactly which ones are needed.

https://www.playstation.com/en-gb/ps5/buy-now/ is the one ive used for the Const

**Comment by outphase84** [comment]
@johnnyboy007 as far as I know, playstation direct is US-only.  I'm not sure any contributors have tested or know how UK's distribution works

**Comment by johnnyboy007** [comment]
Ok no worries, thanks for your response
