### ISSUE TITLE
Users are directed to the queue regardless of which edition they choose

### ISSUE THREAD

**Issue by camtheperson** [camtheperson/get-my-ps5#36]
Currently, the bot directs people to the site as soon as a queue starts forming. However, the queue itself is edition-agnostic, meaning a user running the script could get directed to the site even when their desired edition isn't available.

It would be nice to more effectively detect which edition is actually in stock, and perhaps only send users to the queue if their desired edition is available.

This is kind of a weird problem, because I imagine most people wouldn't mind either edition, period. But I'm not entirely sure how to solve this one at the moment.

Any other thoughts here?

**Comment by outphase84** [comment]
@camtheperson no good way to do this, really. Sony initiates prequeueing before any stock is added. Prequeue seems to last 10-30 minutes before stock is loaded and queued users get access.

Closest approximation would be to queue and then launch a function to check stock on both versions, but this is questionable as previous drops have added one to start, then the other shortly after.

**Comment by camtheperson** [comment]
This project is no longer maintained. Closing this out.
