### ISSUE TITLE
Timing Out, Won't run on its own

### ISSUE THREAD

**Issue by lkspies** [camtheperson/get-my-ps5#38]
Running on Windows 10 from Documents folder. Node was installed into my program files.

I am getting a timeout error that precents the bot from running on its own for long periods of time.  Highest number of tries i got was 297.  This has been pretty consistent at failing around the 30 try mark.  Below is the full dump of error message:

C:\Users\thund\Documents\PS5\get-my-ps5-master\get-my-ps5-master\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:106
        return new Promise((fulfill) => (this._maximumTimer = setTimeout(fulfill, this._timeout))).then(() => new Errors_js_1.TimeoutError(errorMessage));
                                                                                                              ^

TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\Users\thund\Documents\PS5\get-my-ps5-master\get-my-ps5-master\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:106:111
npm ERR! code 1
npm ERR! path C:\Users\thund\Documents\PS5\get-my-ps5-master\get-my-ps5-master
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node index

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thund\AppData\Local\npm-cache\_logs\2020-12-12T17_39_33_233Z-debug.log

**Comment by outphase84** [comment]
@lkspies fixed in upcoming 1.2, see linked pull request if you would like to implement prior to 1.2's release
