### ISSUE TITLE
Sony will ban your IP if you run this script for too long

### ISSUE THREAD

**Issue by sfilargi** [camtheperson/get-my-ps5#39]
After running it for 12 hours, I now get the follow message from all my devices at home:

```
Access Denied
You don't have permission to access "http://direct.playstation.com/" on this server.

Reference #18.df467b68.1607800613.812b0a7 
```

**Comment by mikeyplaut** [comment]
same, opening an incognito tab seems to allow you to login

**Comment by camtheperson** [comment]
@sfilargi Thanks for bringing this up. I'm adding some notes about this to our core readme file in the next release.

Ultimately, the solution here isn't gonna come from any code I write. It's gonna come from using a VPN and understanding the risk (which the updated docs speak to).

Thanks again! Closing this out.

**Comment by ReyHaynes** [comment]
12 hours is dangerously long to run this but I've also used the bot for 24 hours without a ban. I took the liberty of adding an additional random 0-5 seconds to the original 5 seconds. Not sure if that helped, or the fact that there were fewer iterations of IP hitting their analytics backlog, but not banned as of yet.

I do also recommend a VPN as well as running this near their usual drop times.
