### ISSUE TITLE
Help please - Termux AndroidOS 

### ISSUE THREAD

**Issue by lauralee11778** [camtheperson/get-my-ps5#4]
![Screenshot_20201210-015907_Termux](https://user-images.githubusercontent.com/70457592/101732656-90415d00-3a8b-11eb-81ff-23bdfdca3504.jpg)
Hey man, so I'm hell bent on getting this to work on my phone. (AndroidOS). I've gotten this far...everything but the last step. I'm using Termux which works pretty well overall, and the Javascript node was not a problem. I even have the zip file downloaded and extracted using a file Mgr. But I'll be honest, my brain is getting fuzzy because this github is knowledge side project in my life (Most important job raising a preschooler, and full time job as Industrial Hygiene Tech and dog mom of 4, and wife, etc). Help,  please? It's gonna be a Christmas gift for my son and his dad/my husband. Thanks 

>  @camtheperson

**Comment by camtheperson** [comment]
Unfortunately, I have zero experience with AndroidOS, and therefore cannot provide support on such a specific use case.

I would encourage you to look into other resources online for getting Node scripts running on AndroidOS, although ideally you'd run this on a PC or Mac if at all possible.

Good luck!
