### ISSUE TITLE
Some users would like the ability to customize their browser

### ISSUE THREAD

**Issue by camtheperson** [camtheperson/get-my-ps5#40]
Ideal implementation:
- Create an `.env-example` file
- Users would copy that file into `.env` to set it up locally
- The `.env` file would include parameters for browser path, and incognito (true/false)
- Ultimately, we should still give the user the option to test the opening of the browser as well

**Comment by jasonraimondi** [comment]
I've added a PR #49 that adds this feature

**Comment by camtheperson** [comment]
This project is no longer maintained. Closing this out.
