### ISSUE TITLE
Maybe an issue?

### ISSUE THREAD

**Issue by Jusdutari** [camtheperson/get-my-ps5#42]
Hi, I do not know anything on this subject. Am I running ok the bot? Do I have some issues? Because it looks weird to me

Last login: Sat Dec 12 18:24:45 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Justins-MacBook-Pro:get-my-ps5-master-2 justindutari$ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> puppeteer@5.5.0 install /Users/justindutari/Downloads/get-my-ps5-master-2/node_modules/puppeteer
> node install.js

Downloading Chromium r818858 - 132.4 Mb [====================] 100% 0.0s 
Chromium (818858) downloaded to /Users/justindutari/Downloads/get-my-ps5-master-2/node_modules/puppeteer/.local-chromium/mac-818858
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN get-my-ps5@1.1.0 No repository field.

added 547 packages from 377 contributors and audited 547 packages in 20.828s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Justins-MacBook-Pro:get-my-ps5-master-2 justindutari$ npm run watch

> get-my-ps5@1.1.0 watch /Users/justindutari/Downloads/get-my-ps5-master-2
> node index

Which version would you like? (disc or digital) disc
Would you like to hear a loud, annoying alarm when we find your PS5? (Y or N) Y
Searching for PlayStation 5 disc edition...
No redirect detected. Trying again...
Number of tries 1

No redirect detected. Trying again...
Number of tries 2

No redirect detected. Trying again...
Number of tries 3

No redirect detected. Trying again...
Number of tries 4

No redirect detected. Trying again...
Number of tries 5

**Comment by camtheperson** [comment]
@Jusdutari Nope. It installed successfully, and the messages you see repeated at the end mean it’s working. 

I’m working on updating the messages so it’s more clear that it’s running correctly. Keep an eye on my Twitter account for an update on when the next version is released.
