### ISSUE TITLE
UI/UX is poor, and will get worse as additional store support is added.

### ISSUE THREAD

**Issue by outphase84** [camtheperson/get-my-ps5#48]
Investigate pushing data into dynamic CLI table.  Need to investigate existing UI options for streaming data to console in table format.

**Comment by ReyHaynes** [comment]
A simple strategically placed `console.clear()` is good enough in this case for every iteration ran. That's what I ended up doing for myself.

**Comment by outphase84** [comment]
@ReyHaynes Which is fine for the current iteration, but becomes problematic when we add additional stores that run asynchronously.  

I'm working on a UI overhaul in general, this is less of an issue and more of a pseudo-user story for that

**Comment by camtheperson** [comment]
This project is no longer maintained. Closing this out.
