### ISSUE TITLE
Script intermittently stops trying after a few hundred attempts

### ISSUE THREAD

**Issue by cpolitz** [camtheperson/get-my-ps5#5]
Had it run to 287 before not trying anymore.  Restarted then started again and stopped in the 300s
node v12.19.0
Windows 10 Enterprise

Let me know if I can provide any additional details

**Comment by camtheperson** [comment]
Update on this issue: https://twitter.com/CamThePerson/status/1337073452201611264?s=20

Closing this ticket out for now. The temporary workaround is to run the script again, although I have an idea for a fix I'll be able to test as soon as I can hit the actual queue page again.

**Comment by cpolitz** [comment]
Thanks, is possible the proliferation of this is causing overload on psdirect creating more false queue pages :)
