### ISSUE TITLE
Feature: alarm when your IP has been banned

### ISSUE THREAD

**Issue by camtheperson** [camtheperson/get-my-ps5#53]
Pretty sure there should be a way to do this based on a response code or something.

**Comment by damm** [comment]
Does sony return a 403 if your IP is banned, or is it more nefarious?

**Comment by austeny** [comment]
Someone (@Bubs) mentioned in Saru's discord that 12/13 7:47 AM that they were IP banned and received an Access Denied message. You could probably parse for an HTML title or h1 for Access Denied and a 403. 

![access_denied_ps_ip_ban](https://user-images.githubusercontent.com/25534058/102146604-49f74f80-3e37-11eb-8ed7-527422337090.png)

**Comment by drootang** [comment]
Can confirm that I received the message @aquafishe posted, although the reference # was different

(fwiw, i was able to get my ps5, so thank you! continuing to monitor to help a friend)

**Comment by camtheperson** [comment]
This project is no longer maintained. Closing this out.
