### ISSUE TITLE
Can't do npm install

### ISSUE THREAD

**Issue by Tenkomanker** [camtheperson/get-my-ps5#54]
I follow the instructions up to typing cmd into the address bar and it opens cmd in the folder, but typing `npm install` just makes it return `'npm' is not recognized as an internal or external command, operable program or batch file.`

**Comment by camtheperson** [comment]
@Tenkomanker Sounds like you didn’t install node. That’s the first step.

Please run the following commands (separately) and then paste the output from each:
`node -v`
`npm -v`

Thanks.

**Comment by Tenkomanker** [comment]
I did install node though, the LTS version right? It even opens up a cmd window if I search and run it. Maybe I installed it wrong?

**Comment by camtheperson** [comment]
Maybe. Please run the commands I noted above and give me the output.

**Comment by Tenkomanker** [comment]
Hey! Sorry for such a late response, but I restarted my PC and reran the node installer for a repair and it got fixed. Thanks!
