### ISSUE TITLE
Preset configuration option for quick launch?

### ISSUE THREAD

**Issue by Contact2020** [camtheperson/get-my-ps5#56]
I'd like to know if there is anything I can do to make it easier/quicker to launch this. Here is my current 5 step process 
everytime I launch the bot.
1) open cmd
2) navigate to bot folder
3) npm run watch
4) select type
5) select yes to alert

How/would it be possible to setup a script or a shortcut that does those 5 steps automatically when I just click on an icon?

**Comment by jasonraimondi** [comment]
If you use [my fork](https://github.com/jasonraimondi/get-my-ps5) ([until this PR is merged](https://github.com/camtheperson/get-my-ps5/pull/49)), you are able to set a .env file to preconfigure `alert` and `type` (and a few other options like check interval and browser). 

A launcher depends on the platform, on mac or linux you can create an executable bash script to launch it. On windows, I think they are called `.bat`? I havent used windows in over a decade so I'm not really sure.

**Comment by camtheperson** [comment]
This project is no longer maintained. Closing this out.

**Comment by jasonraimondi** [comment]
If people want to use a version of this project WITH this MR, please feel free to use https://github.com/jasonraimondi/get-my-ps5

It is not actively maintained, but at least it contains this MR.
