### ISSUE TITLE
Puppeteer installation failure on M1 Macs

### ISSUE THREAD

**Issue by winfieldxu** [camtheperson/get-my-ps5#57]
npm ERR! code 1
npm ERR! path /*/get-my-ps5/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64:

Ref: [https://chromium.googlesource.com/chromium/src.git/+/master/docs/mac_arm64.md](url)

**Comment by camtheperson** [comment]
This project is no longer maintained. Closing this out.
