### ISSUE TITLE
All Script comes up as missing?

### ISSUE THREAD

**Issue by doomed024** [camtheperson/get-my-ps5#58]
Hey all,

Trying to get npm run watch to work but I get kicked an error saying the script is missing. I also tried npm open and npm sound and it gave me the same error.

Steps I take:
run cmd (admin)
npm install
npm run watch (no dice)

node -v v15.10.0
npm -v 7.5.3

I do have a VPN set up and this thing HAS worked for me in the past but I gave up and went on to other things and now im trying to hunt again.

**Comment by camtheperson** [comment]
This project is no longer maintained. Closing this out.
