### ISSUE TITLE
Is this still active and working?

### ISSUE THREAD

**Issue by ianprice943** [camtheperson/get-my-ps5#60]
I've had this script running for the past week now, and there have been two different Sony Direct restocks in that time, and this script has not alerted me, put me in queue, etc. 

I have been using a vpn the whole time, and changing the IP of it every 12 hours or so, so I know I'm not IP banned.

**Comment by camtheperson** [comment]
Nope, this project hasn't been maintained for awhile. I just added a note about it to the top of the README about it.
