### ISSUE TITLE
Error after running npm run watch

### ISSUE THREAD

**Issue by cmwetherell** [camtheperson/get-my-ps5#7]
npm ERR! code 1
npm ERR! path /Users/xxx/Downloads/get-my-ps5-master
npm ERR! command failed
npm ERR! command sh -c node index

Steps I fdollowed:

Doanloaded and unzipped
navigated to directory
npm install
npm run watch
type disc
error

Cheers, thanks for the help

**Comment by camtheperson** [comment]
Just merged a fix. Update here: https://twitter.com/CamThePerson/status/1337153618277851136

Pull the latest, run npm (or yarn) install, and it should be good.

**Comment by cmwetherell** [comment]
Too bad I didn't see this before today's drop :)

Will be trying tomorrow. TY!
