### ISSUE TITLE
exception not handled in checkForPlayStationRedirect async await

### ISSUE THREAD

**Issue by jaredhensley** [camtheperson/get-my-ps5#8]
(node:76664) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 69.192.7.202:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
(node:76664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:76664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I will follow up with a PR later today.

**Comment by camtheperson** [comment]
Just merged a fix. Update here: https://twitter.com/CamThePerson/status/1337153618277851136

Pull the latest, run npm (or yarn) install, and it should be good.

**Comment by jaredhensley** [comment]
> Just merged a fix. Update here: https://twitter.com/CamThePerson/status/1337153618277851136
> 
> Pull the latest, run npm (or yarn) install, and it should be good.

I don't think this was fixed, there is no exception handling in this async await.  Errors are still being thrown from time to time.  The exception needs to be handled and then continue on, effectively ignoring the exception.

**Comment by outphase84** [comment]
Fixed in 1.2

**Comment by outphase84** [comment]
@jaredhensley see the linked pull request prior to 1.2 release -- you can merge code into current build to resolve this issue, or wait for 1.2 to drop and fix will be in there
